# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5986aed6c82b6e06170692959607093ec3133653f4594dc29ec85b0624b4f25ea101b73309646f9107705c63e8720e6e68ebacc6351960e8ad7f062d5e4c6538

test:
  secret_key_base: 5902ee5e8116cdfcfdd8c2a5b6c64cbd412a2922eb5c4d9a227ffc82895ad912d8387297a0a903cf8bd6c158b0c0d5a4264f48989385e58282f4dc5efd854f20

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
